#:schema node_modules/wrangler/config-schema.json
name = "sublinkworker"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "3b9e9d4d7dc64ee69095f72b1a655e5a" }
]

[assets]
directory = "./public"
